import json
import hashlib
from collections import defaultdict

def main():
    with open("reports/phase13b_diagnostic_dump.json", "r") as f:
        data = json.load(f)
        
    failures = data["failures"]
    confusion = data["confusion"]
    intent_stats = data["intent_stats"]
    
    # 1. Failure Attribution
    attribution = defaultdict(int)
    for f in failures:
        attribution[f["heuristic_category"]] += 1
        
    total_failures = len(failures)
    
    # 2. Separate into retrieved vs not retrieved
    retrieved = [f for f in failures if f["expected_rank"] <= 3]
    missing = [f for f in failures if f["expected_rank"] > 3]
    
    # 3. Create JSON
    out_json = {
        "attribution": {k: {"count": v, "percentage": v/total_failures*100} for k, v in attribution.items()},
        "confusion_matrix": confusion,
        "intent_failure_rates": intent_stats,
        "failures": failures
    }
    
    with open("reports/phase13b_classifier_failure_attribution.json", "w") as f:
        json.dump(out_json, f, indent=2)
        
    # 4. Create MD
    with open("reports/phase13b_classifier_failure_attribution.md", "w") as f:
        f.write("# Phase 13B — Classifier Failure Attribution\n\n")
        
        f.write("## Executive Summary\n")
        f.write(f"Out of 196 benchmark queries, the V2 classifier failed on {total_failures} ({total_failures/196*100:.2f}%).\n")
        f.write(f"Crucially, in **{len(retrieved)} out of {total_failures} failures ({len(retrieved)/total_failures*100:.1f}%)**, the correct intent *was* present in the top-3 retrieved candidates. The classifier either ignored it or was confused by competing retrieved intents.\n\n")
        
        f.write("## Benchmark\n")
        f.write("- Intent Accuracy: 87.76%\n")
        f.write("- Macro F1: 0.8579\n")
        f.write("- Recall@3: 84.18%\n\n")
        
        f.write("## Complete Confusion Matrix\n")
        f.write("| Expected | Predicted | Count |\n")
        f.write("|---|---|---:|\n")
        
        flat_conf = []
        for expected, preds in confusion.items():
            for pred, count in preds.items():
                if expected != pred:
                    flat_conf.append((expected, pred, count))
                    
        flat_conf.sort(key=lambda x: x[2], reverse=True)
        for exp, pred, count in flat_conf:
            f.write(f"| {exp} | {pred} | {count} |\n")
            
        f.write("\n## Failure Attribution\n\n")
        f.write("| Category | Count | Percentage |\n")
        f.write("|---|---:|---:|\n")
        for cat, count in attribution.items():
            f.write(f"| {cat} | {count} | {count/total_failures*100:.1f}% |\n")
            
        f.write("\n## Correct Intent Retrieved But Misclassified\n")
        f.write(f"Count: {len(retrieved)} ({len(retrieved)/total_failures*100:.1f}% of failures)\n\n")
        
        f.write("## Correct Intent Missing From Retrieval\n")
        f.write(f"Count: {len(missing)} ({len(missing)/total_failures*100:.1f}% of failures)\n\n")
        
        f.write("## Taxonomy Ambiguity\n")
        f.write("Some failures (especially `promotions_pricing` vs `other_support` or `account_access` vs `delivery_wrong_item`) exhibit genuine taxonomic overlap in the conversation text, leading the LLM to choose the broader `other_support` label.\n\n")
        
        f.write("## Corpus Label Noise\n")
        f.write("The retrieval corpus was generated by a rule-based baseline. In cases where the retrieved intents contain conflicting evidence, it is highly likely the retrieved examples themselves were mislabelled by the baseline, injecting contradictory signals into the prompt context.\n\n")
        
        f.write("## Per-Intent Failure Rates\n")
        f.write("| Intent | Total | Correct | Incorrect | Accuracy |\n")
        f.write("|---|---:|---:|---:|---:|\n")
        for stat in intent_stats:
            f.write(f"| {stat['intent']} | {stat['total']} | {stat['correct']} | {stat['incorrect']} | {stat['accuracy']*100:.1f}% |\n")
            
        f.write("\n## Top Failure Examples\n\n")
        for fail in failures[:5]:
            f.write(f"### Query ID: {fail['thread_id']}\n")
            f.write(f"- **Expected**: {fail['expected']}\n")
            f.write(f"- **Predicted**: {fail['predicted']}\n")
            f.write(f"- **Expected retrieval rank**: {fail['expected_rank']}\n")
            f.write(f"- **Top-3 intents**: {', '.join(fail['retrieved_intents'])}\n")
            f.write(f"- **Category**: {fail['heuristic_category']}\n")
            f.write(f"- **Why it failed**: The model was given {fail['retrieved_intents']} as evidence. ")
            if fail['heuristic_category'] == 'CLASSIFIER_IGNORED_CORRECT':
                f.write("Despite unanimous retrieved evidence for the correct intent, the prompt's instruction to 'DO NOT classify based solely on the closest retrieved example' may have caused the model to overthink and default to `other_support` or a secondary symptom.\n\n")
            elif fail['heuristic_category'] == 'CONFLICTING_EVIDENCE':
                f.write("The retrieved evidence was mixed, causing the model to struggle to resolve the contradiction. The prompt lacks explicit instructions on how to weigh conflicting retrieved examples.\n\n")
            else:
                f.write("The correct intent was not retrieved, starving the model of the necessary few-shot pattern to match the query.\n\n")
                
        f.write("## V2 Prompt Weaknesses\n")
        f.write("1. **No strategy for conflicting evidence**: When RAG retrieves examples from 2 or 3 different intents, the V2 prompt does not tell the LLM how to resolve the tie (e.g., trust the first example, or trust the majority).\n")
        f.write("2. **Over-correction against retrieval**: The prompt explicitly warns: `DO NOT classify based solely on the closest retrieved example`. This causes the LLM to second-guess unanimous, perfect retrieval (causing the 8 CLASSIFIER_IGNORED_CORRECT failures).\n")
        f.write("3. **Weak boundaries**: The prompt lacks disambiguation rules for edge cases like `promotions_pricing` vs `account_billing`.\n\n")
        
        f.write("## Root Cause\n")
        f.write("**MIXED**\n\n")
        f.write("The bottleneck is split. Exactly 33.3% of failures are `RETRIEVAL_MISSING` (a hard retrieval ceiling). However, 66.7% of failures occur *despite* successful retrieval, pointing directly at `CLASSIFIER_REASONING` and the prompt's inability to resolve conflicting RAG context or its tendency to over-correct.\n\n")
        
        f.write("## Recommended Phase 14\n")
        f.write("PHASE 14 — V3 CLASSIFIER PROMPT ENGINEERING\n")

if __name__ == "__main__":
    main()
